# Generated by Django 5.2.11 on 2026-02-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(blank=True, help_text='Optional external OPIS Truckstop ID reference from CSV.', null=True)),
                ('name', models.CharField(help_text='Fuel station name (brand + location identifier).', max_length=255)),
                ('address', models.CharField(help_text='Street address or highway exit description for this station.', max_length=255)),
                ('city', models.CharField(db_index=True, help_text='City name for this station.', max_length=100)),
                ('state', models.CharField(db_index=True, help_text='Two-letter US state code (e.g., TX, CA).', max_length=2)),
                ('rack_id', models.IntegerField(blank=True, db_index=True, help_text='Rack/terminal region identifier from CSV.', null=True)),
                ('latitude', models.FloatField(blank=True, db_index=True, help_text='Latitude in decimal degrees.', null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, help_text='Longitude in decimal degrees.', null=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=3, help_text='Price per gallon in USD (e.g., 3.599).', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this station record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this station record was last updated.')),
            ],
            options={
                'verbose_name': 'Fuel station',
                'verbose_name_plural': 'Fuel stations',
                'ordering': ['state', 'city', 'name'],
                'indexes': [models.Index(fields=['state', 'rack_id'], name='station_state_rack_idx'), models.Index(fields=['latitude', 'longitude'], name='station_lat_lon_idx')],
            },
        ),
    ]
